config/routes.rb
Rails.application.routes.draw do
 root "posts#index"

resources :posts do
 resources :comments, only: [:new, :create, :destroy]
end


end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post

	validates :body, presence: true, length: {minimum: 30}
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	validates :body, presence: true
	validates :title, presence: true

	def self.from_param(param)
		where(author: NameCase(param))
	end

	def published?
		publication.present? and url.present? and published_at.present?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	# Find the post using the post_id in the URL
  	@post = Post.find(params[:post_id])
  	# Create a new comment for that @post
  	@comment = @post.comments.new
  end

  def create
  	# Find the post using the post_id in the URL
  	@post = Post.find(params[:post_id])
  	# Create a new comment for that @post
  	@comment = @post.comments.new(comment_params)
  	# if it sames
  	if @post.save
  	# redirect to
  	redirect_to @post
  else
  	render :new
  end
end

  def destroy
  	@post = Post.find(params[:post_id])
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  	redirect_to @post
  end

  private
  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]

  def index
    if params[:author].present?
      @posts = Post.from_param(params[:author])
    else
    	# We assign an instance variable
    	@posts = Post.all
    	# Rails sends it to the view (index)
    	#Rails renders the view (index)
    end
  end



  def show
  	#We assign an instance variable
  	#Rails sends it to the view if it's there (show)
  	#Rails renders the view

    #Look for comments on this post
    @comments = @post.comments.all
  end

  def new
    #Provide instance variable for form builder
	 @post = Post.new
  end

  def create
    @post = Post.new(post_params) # Make the data secure (post_params)
  	# Save the data from the form
    if @post.save
    	redirect_to @post
    else
      render :new
    end
  end

  def edit
  	# Find the post to edit
  	# Rails gives it to the view
  end

  def update
  	# Make the data secure
    if @post.update(post_params)
    	# Save the data from the form
    	# If it saves
    	redirect_to @post
  	else
    	# render the edit page again
      render :edit
    end
  end

  def destroy
  	# Find the post for deleting
  	# Delete taht post
    @post.destroy
    
  	redirect_to root_path
  end

  private
  #Only allow this stuff
  def post_params
    params.require(:post).permit(:title, :body, :publication, :url, :published_at, :author, :pull_quote)
  end


  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<h1>Comment on <em>"<%= @post.title %>"</em> below.</h1>
<%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>

<%= f.input :body, placeholder: "Write your comment here..." %>
<%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |form| %>
	<%= form.input :title %>
	<%= form.input :author %>
	<%= form.input :body %>
	<%= form.input :publication, label: "Where first published" %>
	<%= form.input :published_at, label: "Date of first publication" %>
	<%= form.input :url, label: "Link to publication"%>
	<%= form.input :pull_quote %>

	<%= form.button :submit %>

	<% end %>

app/views/posts/edit.html.erb
<h1>Editing '<%= @post.title %>'</h1>
 <!-- reference the form partial -->

<%= render "form" %>

app/views/posts/index.html.erb
<header>
<h1>
<%= link_to "Writing Ruby", root_path %>
</h1>

<!-- Carousel -->
<div class="carousel">
	<h3>The first draft of everything is shit.</br><cite>– Hemmingway</cite>
	</h3>
</div>
</header>

<!-- Paginator -->

<nav class="pagination pagination__top">
<!-- Provide pagination later with Kaminari Gem. -->
</nav>

<!-- A list of posts -->
<section class="posts">

<!-- Loop over posts -->
<% @posts.each do |post| %>

<section class="post">

	<!-- Title of post -->
	<h2><%= link_to post.title, post %></h2>
	<!-- Truncated body of post -->
	<p><%= truncate post.body, length: 90, separator: ' ' %></p>

	<p>
	<!-- When it was posted -->
	<small>Posted <%= time_ago_in_words post.created_at %> ago.
	<!-- If it was published -->
		<% if post.published?%>
		<span class="separator">•</span>
		<!-- Where it was published -->
		<%= link_to post.publication, post.url %>
		Published in <%= link_to post.publication, post.url %>
		<!-- When it was published -->
		<!-- <%= time_ago_in_words post.published_at %> ago. -->
		<% end %>
		</small>
	</p>

</section>

<% end %>

</section>

app/views/posts/new.html.erb
<h1>New Post</h1>
<!-- Form goes here -->

<%= render "form" %>

app/views/posts/show.html.erb
<section class="post__title">
	<!-- Access the Post with instance variable set in controller -->
	<h2><%= @post.title%></h2>
	<!-- Include byline, link to filter results by author -->
	<p>By <%= link_to @post.author, root_path(author: @post.author.downcase.to_param) %></p>

	<p>
		<small>Posted <%= time_ago_in_words @post.created_at %> ago.</small>
	</p>

	<% if @post.published?%>
		<p>
			<small>Published in <%= link_to @post.publication, @post.url%> on <%= @post.published_at %></small>
		</p>
	<% end %>

	<div class="actions">
		<%= link_to "home", root_path, class: "actions__link"%>
		<span class="separator">•</span>
		<%= link_to "edit", edit_post_path, class: "actions__link" %>
		<span class="separator">•</span>
		<%= link_to "delete", post_path, method: :delete, class: "actions__link" %>
	</div>

<!-- <%= link_to "Home", root_path %> -->

<div>
	<% if @post.pull_quote.present? %>
	<blockquote><%= @post.pull_quote%></blockquote>
	<% end %>
</div>

</section>

	<section class="post__body">
	<%= simple_format @post.body %>

<hr>
	<h3>Comments</h3>
	<h4><%= link_to "Add a Comment", new_post_comment_path(@post) %></h4>

	<% @comments.each do |comment| %>
		<div class="post__comment">
		<%= simple_format comment.body %>

		<p>
		<small><%= time_ago_in_words comment.created_at%></small>
		<small><%= link_to "Remove comment", post_comment_path(@post, comment), method: :delete %></small>
		</p>

		</div>
	<% end %>

</section>